### ISSUE TITLE
Collect / organize curriculum-specific tips

### ISSUE THREAD

**Issue by ha0ye** [UF-Carpentry/Coordination#106] opened 2019-05-09 19:34 UTC
We often have experience or post-workshop feedback on what worked well and what didn't. A public record of this info would help for organizing and running future workshops.

It's unclear what the ideal space for this would be - @justinmillar started a repo specifically for the geospatial workshop https://github.com/UF-Carpentry/geospatial-pilot-notes

**Comment by picardis** [comment] 2019-05-22 19:17
Duplicate of #96

**Closed by picardis** 2019-05-22 19:17 UTC
